source 'https://rubygems.org'
gem 'mysql2'
gem 'dbi'
gem 'dbd-mysql'
gem 'rconfig'
gem 'logger'
gem 'mechanize'
gem 'nokogiri', '~> 1.6.2.1'
gem 'aws-sdk'
gem 'google-api-client', '~> 0.7'
gem  'thin'
gem 'trollop'
gem 'openssl-extensions'

